### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by LDsylsp** [joeyHXD/aichat_chatGPT_API#3]
[2023-03-18 22:03:05,896 群AI&chatGPT] ERROR: <class 'TypeError'> occured when ai_chat handling message 1228709217.
[2023-03-18 22:03:05,896 群AI&chatGPT] ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\Users\Kino\hoshinosp\hoshino\service.py", line 191, in wrapper
    return await func(self.bot, ctx)
  File "D:\Users\Kino\hoshinosp\hoshino\tool.py", line 56, in decorated
    if not await not_conflict(args[0], ev):
  File "D:\Users\Kino\hoshinosp\hoshino\tool.py", line 27, in not_conflict
    service_funcs.extend(t.find_handler(event))
TypeError: 'NoneType' object is not iterable

想问下大佬这个是反并发的问题吗，我的hoshino确实不是最新版本，因为魔改了许多所以不太想更新，有没有办法可以解决或者把反并发的功能去掉？

**Comment by joeyHXD** [comment]
是的，反并发和星乃版本不兼容，需要更新
https://github.com/lhhxxxxx/hoshino_tool/issues/1
